[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


remappings = ['@uniswap/v4-core/=lib/v4-core/',
'forge-gas-snapshot/=lib/v4-core/lib/forge-gas-snapshot/src/',
'forge-std/=lib/v4-core/lib/forge-std/src/',
'permit2/=lib/v4-periphery/lib/permit2/',
'solmate/=lib/v4-core/lib/solmate/',
'@uniswap/v4-periphery/=lib/v4-periphery/',
'@uniswap/v3-core/=lib/v3-core/contracts/',
'@uniswap/v3-periphery/=lib/v3-periphery/contracts/']